// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package ˮgoPackageˮ

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// newˮPrimaryClassˮ is a goModule method implementation.
func (self *goModuleImpl) newˮPrimaryClassˮ(nameArg string) (goˮPrimaryClassˮ, error) {
	return nil, errors.ErrUnsupported
}

// defaultˮPrimaryClassˮGetter is a goModule property getter method implementation.
func (self *goModuleImpl) defaultˮPrimaryClassˮGetter() (goˮPrimaryClassˮ, error) {
	return nil, errors.ErrUnsupported
}

// goˮPrimaryClassˮImpl is an empty implementation of goˮPrimaryClassˮ.
type goˮPrimaryClassˮImpl struct{}

var _ goˮPrimaryClassˮ = (*goˮPrimaryClassˮImpl)(nil)

// greetingGetter is a goˮPrimaryClassˮ property getter method implementation.
func (self *goˮPrimaryClassˮImpl) greetingGetter() (string, error) {
	return "", errors.ErrUnsupported
}
